config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get '/sign_up', to: 'users#new'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_in', to: 'sessions#destroy'
  
  resources :users, only: %i[create]
  resources :categories
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true

  belongs_to :author, class_name: 'User'

  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user

  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories

  has_one_attached :image, dependent: :destroy

  def vote_count
    votes.count
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :user_name, uniqueness: true
  validates :user_name, presence: true
  validates :user_name, length: { in: 3..10 }
  validates :password, length: { in: 6..20 }

  has_many :articles, foreign_key: :author_id, dependent: :destroy

  has_many :votes, dependent: :destroy
  has_many :voted_articles, through: :votes, source: :article

  def already_voted?(article)
    voted_articles.include?(article) ? true : false
  end

  def up_vote(article)
    if already_voted?(article)
      false
    else
      voted_articles << article
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end

  def user_signed_in?
    current_user ? true : false
  end

  def require_login
    return if user_signed_in?

    flash[:alert] = 'You must be logged in to access this section'
    redirect_to sign_in_path
  end

  helper_method :user_signed_in?, :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    category = Category.find(params[:article][:categories])
    if current_user.articles << @article && @article.categories << category
      flash[:notice] = 'Article successfully created.'
      redirect_to category_path(category)
    else
      flash.now[:alert] = 'Incorrect input. Please try again.'
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Article is successfully updated...'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    flash[:notice] = 'Article successfully deleted.'
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.joins(:article_categories).order(priority: :desc).distinct
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.order(created_at: :desc)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category successfully created.'
      redirect_to root_path
    else
      flash.now[:alert] = 'Incorrect input. Please try again.'
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(user_name: params[:session][:user_name])
    if user&.authenticate(params[:session][:password])
      session[:id] = user.id
      flash[:notice] = 'Successfully logged in.'
      redirect_to root_path
    else
      flash.now[:alert] = 'Wrong name or password. Please try again.'
      render 'new'
    end
  end

  def destroy
    session[:id] = nil
    flash[:notice] = 'You have logged out.'
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Account successfully created.'
      session[:id] = @user.id
      redirect_to :root
    else
      flash[:alert] = 'Incorrect input. Please try again.'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    current_user.up_vote(article)
    redirect_back fallback_location: root_path
  end

  def destroy
    vote = Vote.find(params[:id])
    vote.destroy
    redirect_back fallback_location: root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def popular_article
    return Article.first unless Vote.any?

    Article.where(id: Vote.group(:article_id).count(:user_id).invert.max[1]).take
  end

  def latest_article(category)
    category.articles.order(created_at: :desc).first
  end

  def get_vote(article)
    current_user.votes.where(article_id: article.id).take
  end

  def display_vote_button(article)
    return unless user_signed_in?

    if current_user.already_voted?(article)
      render 'articles/vote', article: article, vote: 'down', method: :delete, path: :article_vote_path
    else
      render 'articles/vote', article: article, vote: 'up', method: :post, path: :article_votes_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_article.html.erb
<div class="article d-sm-flex">
  <div class="article-img">
    <%= image_tag(article.image)if article.image.attached? %>
  </div>
  <div class="card"">
    <div class="card-body">
      <h5 class="card-title"><%= article.title %></h5>
      <small class="card-subtitle mb-2 text-muted font-italic">Posted <%= time_ago_in_words(article.created_at) %> ago</small>
      <p class="card-text"><%= article.text %></p>
      <p class="card-text author"><small class="text-muted">By <%= article.author.user_name %></small></p>
      
      <% if article.author == current_user %>
        <%= link_to 'Edit', edit_article_path(article), class: "btn-sm btn-primary" %>
        <%= link_to article_path(article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"} do %>  
          <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
      <% end %>

      
      <%= display_vote_button(article) %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
    <form class="row">
        <div class="form-group">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :text, "Text" %>
            <%= f.text_area :text, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :category, "Choose Category" %>
            <%= collection_select(:article, :categories, Category.all, :id, :name, {}, {class: "form-control"})%>
        </div>
        <div class="form-group">
            <%= f.label :image, "Upload image" %>
            <%= f.file_field :image, class: "form-control-file", direct_upload: true %>
        </div>
        <%= f.submit class: "btn btn-primary mb-3"%>
    </form>
<% end %>

app/views/articles/_vote.html.erb
<div class= "vote float-right">
    <%= link_to (method == :post ? article_votes_path(article) : article_vote_path(article, get_vote(article))), method: method, class: "vote-btn" do %>
        <i class="fa fa-thumbs-<%=vote%>" aria-hidden="true"></i>
    <% end %>
    <p class="vote-count text-primary"><%= article.vote_count %></p>
</div>

app/views/articles/edit.html.erb
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-md-5 col-sm-6">
            <h2>Edit article</h2>
            <%= render 'form' %>
        </section>
    </section>
</section>

app/views/articles/new.html.erb
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-md-3 col-sm-3"></section>
        <section class="col-12 col-md-5 col-sm-6">
            <h2>Create a new article</h2>
            <%= render 'form' %>
        </section>
        <section class="col-12 col-md-4 col-sm-3">
            <%= link_to 'Create a new Category', new_category_path, class: "btn btn-primary" %>
        </section>
    </section>
</section>

app/views/categories/_category.html.erb
<div class="category">
    <%= image_tag latest_article(category).image, class: "category-image" if latest_article(category).image.attached? %>
    <%= link_to category.name, category_path(category), class: "category-name ml-3" %>
    <span class="badge badge-light priority mr-3"><%= category.priority %></span>
    <p class="category-text ml-3"><%= latest_article(category).title %></p>
</div>

app/views/categories/_category_carousel.html.erb
<div class="banner">
    <%= image_tag popular_article.image, class: "img-fluid w-100 banner-img" if popular_article.image.attached? %>
    <div class="banner-desc mx-3">
        <%= link_to popular_article.title, article_path(popular_article), class: "banner-title" %>
        <p class="banner-text"><%= popular_article.text %></p>
    </div>
    <%= display_vote_button(popular_article) %>
</div>

app/views/categories/index.html.erb
<% if @categories.any? %>
    <%= render 'category_carousel' %>
    <div class="categories d-sm-flex">
        <%= render @categories %>
    </div>
<% end %>

app/views/categories/new.html.erb
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-md-5 col-sm-6">
            <%= form_with model: @category do |f| %>
                <form class="row">
                    <div class="form-group">
                        <%= f.label :name, "Name" %>
                        <%= f.text_field :name, class: "form-control" %>
                        <div class="small text-danger">
                            <%= "Category name #{@category.errors.messages[:name][0]}" if @category.errors.messages[:name][0]  %>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :name, "Priority" %>
                        <%= f.text_field :priority, class: "form-control" %>
                    </div>
                    <%= f.submit "Create category",  class: "btn btn-primary"%>
                </form>
            <% end %>
        </section>
    </section>
</section>

app/views/categories/show.html.erb
<% if @articles.any? %>
    <div class="articles d-sm-flex flex-wrap">
        <%= render partial: 'articles/article', collection: @articles %>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
    <% flash.each do |key, value|  %>
        <div class="alert 
            <%= "alert-danger" if key == "alert" %>
            <%= "alert-success" if key == "notice" %>" role="alert">
            <%= value %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white h-75">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">WildStyle<span class="dot">•</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav  flex-grow-1">
        <li class="nav-item ml-lg-auto">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">HOME</a>
        </li>
        
        <% if Category.any? %>
          <% Category.first(3).each do |category| %>  
            <li class="nav-item">
              <a class="nav-link" href="<%=category_path(category)%>"><%= category.name.upcase %></a>
            </li>
          <% end %>
        <% end %>

        <%= link_to new_article_path, class: "btn btn-sm btn-primary ml-lg-auto pencil" do %>  
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <% end %>

        <% if user_signed_in? %>
            <li class="nav-item"><%= link_to current_user.user_name.upcase!, root_path, class: "nav-link text-underline" %></li>
            <li class="nav-item"><%= link_to 'SIGN OUT', sign_in_path, method: :delete, class: "nav-link" %></li>
        <% else %>
            <li class="nav-item"> <%= link_to 'LOG IN', sign_in_path, class: "nav-link" %> </li>
            <div class="nav-item"><div class="nav-link px-0">|</div></div>
            <li class="nav-item"> <%= link_to 'REGISTER', sign_up_path, class: "nav-link" %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Article</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/d86848cfe0.js"></script>
  </head>

  <body class="container-fluid">
    <!-- header -->
    <%= render 'layouts/header' %>
    <!-- main -->
    <main>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
    <!-- footer -->

  </body>
</html>

app/views/users/new.html.erb
<section class="container-fluid">
    <section class="row justify-content-center">
        <section class="col-12 col-md-3 col-sm-6">
            <h2 >Sign Up</h2>
            <%= form_with model: @user, local: true do |f| %>
                <form class="row">
                    <div class="form-group">
                        <%= f.label :user_name %>
                        <%= f.text_field :user_name, class: "form-control", placeHolder: "Enter Username" %>
                        <div class="small text-danger">
                            <%= "Username #{@user.errors.messages[:user_name][0]}" if @user.errors.messages[:user_name][0]  %>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :password %>
                        <%= f.password_field :password, class: "form-control", placeHolder: "Password" %>
                        <div class="small text-danger">
                            <%= "Password #{@user.errors.messages[:password][0]}" if @user.errors.messages[:password][0] %>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= f.label :password_confirmation %>
                        <%= f.password_field :password_confirmation, class: "form-control", placeHolder: "Password Confirmation" %>
                    </div>
                    <%= f.submit 'Sign Up', class: "btn btn-primary" %>
                </form>
            <% end %>
        </section>
    </section>
</section>